version: '3'

services:
  dockerauth:
    image: cesanta/docker_auth
    ports:
      - "5001:5001"
    volumes:
      - ./docker-registry/config:/config:ro
      - ./docker-registry/log:/logs
    command: /config/registry_auth_config.yml
    restart: always

  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/server.crt
      REGISTRY_HTTP_TLS_KEY: /certs/server.key
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_AUTH: token
      REGISTRY_AUTH_TOKEN_REALM: https://localhost:5001/auth
      REGISTRY_AUTH_TOKEN_SERVICE: "Docker registry"
      REGISTRY_AUTH_TOKEN_ISSUER: "Auth Service"
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/server.crt
    volumes:
      - ./docker-registry/data:/var/lib/registry
      - ./docker-registry/config/certs:/certs:ro

  web:
    build: ./web
    ports:
      - 3000:3000
    environment:
      BULLSEYE_RUNNER_HOST: 'runner:3001'
      DOCKER_REGISTRY_HOST: 'registry:5000'
      DOCKER_REGISTRY_AUTH_HOST: 'dockerauth:5001'

  runner:
    build: ./runner
