roles:
  - web
is_vagrant: true
user: vagrant
app_path: /vagrant/
mysql_server:
  username: web
  password: db_password
  database: bullseye_production
admin:
  username: admin
  password: admin_password
hosts:
  web:
    ip_addr: 10.123.0.2
    internal_ip_addr: 10.123.0.2
    service: 10.123.0.2:80
  docker_registry:
    ip_addr: 10.123.0.3
    internal_ip_addr: 10.123.0.3
    registry_service: 10.123.0.3:5000
    registry_auth_service: 10.123.0.3:5001
  runner:
    ip_addr: 10.123.0.4
    service: 10.123.0.4:80
