roles:
  - web
is_vagrant: true
user: vagrant
app_path: /vagrant/
mysql_server:
  username: web
  password: db_password
  database: bullseye_production
admin:
  username: admin@localhost
  password: admin_password
host:
  bullseye_runner: 10.123.0.2
  docker_registry: 10.123.0.3:5000
  docker_registry_auth: 10.123.0.3:5001
