web:
  ip_addr: 35.221.69.9
  service: www.finals.ctf.codeblue.jp:80
  service_url: http://www.finals.ctf.codeblue.jp
docker_registry:
  ip_addr: 35.221.70.238
  registry_service: registry.finals.ctf.codeblue.jp:5000
  registry_auth_service: registry.finals.ctf.codeblue.jp:5001
runner:
  ip_addr: 10.146.0.4
  service: 10.146.0.4:80
