version: '3'

services:
  dockerauth:
    image: cesanta/docker_auth
    ports:
      - "5001:5001"
    environment:
      BULLSEYE_WEB_URL: http://web:3000
      BULLSEYE_API_AUTH_TOKEN: BULLSEYE_AUTH_TOKEN
    volumes:
      - ./docker-registry/config:/config:ro
      - ./docker-registry/log:/logs
    command: /config/registry_auth_config.yml
    restart: always

  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_AUTH_TOKEN_REALM: https://localhost:5001/auth
      REGISTRY_AUTH_TOKEN_ISSUER: "Auth Service"
      REGISTRY_NOTIFICATIONS_ENDPOINTS: "- name: bullseye-web\n  url: http://localhost:3003/internal_api/v1/registry_event"
    volumes:
      - ./docker-registry/data:/var/lib/registry
      - ./docker-registry/config/certs:/certs:ro
      - ./docker-registry/config/registry_config.yml:/etc/docker/registry/config.yml:ro

  web:
    build: ./web
    ports:
      - 3000:3000
    environment:
      BULLSEYE_RUNNER_HOST: 'runner:3001'
      BULLSEYE_API_AUTH_TOKEN: 'BULLSEYE_AUTH_TOKEN'
      DOCKER_REGISTRY_HOST: 'registry:5000'
      DOCKER_REGISTRY_AUTH_HOST: 'dockerauth:5001'

  runner:
    build: ./runner
    ports:
      - 3001:3000
    environment:
      BULLSEYE_WEB_WEBHOOK_URL: 'http://web:3000/webhook'
